engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
ratings:
  paths:
  - lib/**
exclude_paths:
- spec/**/*
- tools/**/*
- index.js
- global.js
- getter.js
