language: node_js

node_js:
  - "6.0.0"
  - "8.9.1"

before_install:
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3.10.8; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm run lint
